# Generated by Django 3.1.3 on 2021-04-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210422_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
