# Generated by Django 3.1.8 on 2021-05-10 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210510_0849'),
        ('order', '0004_auto_20210510_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.variants'),
        ),
    ]
