# Generated by Django 3.1.3 on 2021-05-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_shopcart_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Mới', 'Mới'), ('Chuẩn bị', 'Chuẩn bị'), ('Đang giao hàng', 'Đang giao hàng'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Mới', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Mới', 'Mới'), ('Đã được chấp nhận', 'Đã được chấp nhận'), ('Đã được chấp nhận', 'Đã được chấp nhận')], default='Mới', max_length=50),
        ),
    ]
