# Generated by Django 3.1.8 on 2021-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210530_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang chờ xác nhận', 'Đang chờ xác nhận'), ('Chuẩn bị giao hàng', 'Chuẩn bị giao hàng'), ('Đang giao hàng', 'Đang giao hàng'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Đang chờ xác nhận', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Mới', 'Mới'), ('Đã được chấp nhận', 'Đã được chấp nhận'), ('Đã hủy', 'Đã hủy')], default='Mới', max_length=50),
        ),
    ]
