# Generated by Django 3.1.8 on 2021-06-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210611_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_pay',
            field=models.CharField(choices=[('Đang chờ xác nhận', 'Đang chờ xác nhận'), ('Chuẩn bị giao hàng', 'Chuẩn bị giao hàng'), ('Đang giao hàng', 'Đang giao hàng'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Chưa thanh toán', max_length=50),
        ),
    ]
