# Generated by Django 3.1.8 on 2021-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_transport_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transport_fee',
            field=models.IntegerField(),
        ),
    ]
