# Generated by Django 3.1.8 on 2021-07-06 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0019_auto_20210706_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWaitingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=5)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('ward', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[('Đang chờ xác nhận', 'Đang chờ xác nhận'), ('Chuẩn bị giao hàng', 'Chuẩn bị giao hàng'), ('Đang giao hàng', 'Đang giao hàng'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Đang chờ xác nhận', max_length=50)),
                ('status_pay', models.CharField(choices=[('Chưa thanh toán', 'Chưa thanh toán'), ('Đã thanh toán', 'Đã thanh toán')], default='Chưa thanh toán', max_length=50)),
                ('delivery', models.CharField(blank=True, max_length=255)),
                ('transport_fee', models.IntegerField()),
                ('ip', models.CharField(blank=True, max_length=30)),
                ('adminnote', models.CharField(blank=True, max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
