# Generated by Django 3.1.3 on 2021-04-15 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210413_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='statusdiscount',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='valuediscount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
