# Generated by Django 3.1.3 on 2021-04-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210415_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='valuediscount',
        ),
        migrations.AddField(
            model_name='product',
            name='pricediscount',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=20),
            preserve_default=False,
        ),
    ]
