# Generated by Django 3.1.3 on 2021-04-16 04:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210415_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tespproduct',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
    ]
