# Generated by Django 3.1.8 on 2021-04-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210423_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
