# Generated by Django 3.1.8 on 2021-05-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210426_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
