# Generated by Django 3.1.8 on 2021-05-06 22:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210507_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.variants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variants',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variants',
            name='tespproduct',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0),
            preserve_default=False,
        ),
    ]
