# Generated by Django 3.1.8 on 2021-05-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210510_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='tespproduct',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
