# Generated by Django 3.1.8 on 2021-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20210512_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
