# Generated by Django 3.1.8 on 2021-06-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_pro_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_code',
        ),
    ]
