# Generated by Django 3.1.8 on 2021-06-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_search',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category_product_detail'),
        ),
    ]
