# Generated by Django 3.1.8 on 2021-06-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20210614_0402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Search',
        ),
    ]
