# Generated by Django 3.1.8 on 2021-06-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_delete_product_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountRAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CameraFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InternaMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdvancedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.amountram')),
                ('batteryperformance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.batteryperformance')),
                ('camerafeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.camerafeature')),
                ('internamemory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.internamemory')),
                ('phonedesign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.phonedesign')),
                ('phonetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.phonetype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('screensize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.screensize')),
                ('specialfeatures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.specialfeatures')),
            ],
        ),
    ]
