# Generated by Django 3.1.8 on 2021-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_amountram_batteryperformance_camerafeature_internamemory_phonedesign_phonetype_productadvancedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryperformance',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
