# Generated by Django 3.1.8 on 2021-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20210614_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
