# Generated by Django 3.1.8 on 2021-07-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_compareproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productadvancedsearch',
            name='amountram',
        ),
        migrations.RemoveField(
            model_name='productadvancedsearch',
            name='batteryperformance',
        ),
        migrations.RemoveField(
            model_name='productadvancedsearch',
            name='camerafeature',
        ),
        migrations.RemoveField(
            model_name='productadvancedsearch',
            name='internamemory',
        ),
        migrations.RemoveField(
            model_name='productadvancedsearch',
            name='phonedesign',
        ),
        migrations.RemoveField(
            model_name='productadvancedsearch',
            name='phonetype',
        ),
        migrations.RemoveField(
            model_name='productadvancedsearch',
            name='screensize',
        ),
        migrations.RemoveField(
            model_name='productadvancedsearch',
            name='specialfeatures',
        ),
        migrations.AddField(
            model_name='productadvancedsearch',
            name='battery_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productadvancedsearch',
            name='camera_3d',
            field=models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productadvancedsearch',
            name='camera_ai',
            field=models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productadvancedsearch',
            name='camera_beauty_effect',
            field=models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productadvancedsearch',
            name='camera_optical_zoom',
            field=models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productadvancedsearch',
            name='camera_slow_motion',
            field=models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
