# Generated by Django 3.1.8 on 2021-07-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20210709_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compare',
        ),
    ]
