# Generated by Django 3.1.8 on 2021-07-09 07:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_delete_compare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', ckeditor_uploader.fields.RichTextUploadingField()),
                ('backcam', ckeditor_uploader.fields.RichTextUploadingField()),
                ('frontcam', ckeditor_uploader.fields.RichTextUploadingField()),
                ('cpu', ckeditor_uploader.fields.RichTextUploadingField()),
                ('memory', ckeditor_uploader.fields.RichTextUploadingField()),
                ('connection', ckeditor_uploader.fields.RichTextUploadingField()),
                ('battery', ckeditor_uploader.fields.RichTextUploadingField()),
                ('utils', ckeditor_uploader.fields.RichTextUploadingField()),
                ('general', ckeditor_uploader.fields.RichTextUploadingField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
