# Generated by Django 3.1.8 on 2021-07-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_compare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmountRAM',
        ),
        migrations.DeleteModel(
            name='BatteryPerformance',
        ),
        migrations.DeleteModel(
            name='CameraFeature',
        ),
        migrations.DeleteModel(
            name='CompareProduct',
        ),
        migrations.DeleteModel(
            name='InternaMemory',
        ),
        migrations.DeleteModel(
            name='PhoneDesign',
        ),
        migrations.DeleteModel(
            name='PhoneType',
        ),
        migrations.DeleteModel(
            name='ScreenSize',
        ),
        migrations.DeleteModel(
            name='SpecialFeatures',
        ),
    ]
