# Generated by Django 3.1.8 on 2021-07-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20210711_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_Product_Detail',
        ),
    ]
