# Generated by Django 3.1.8 on 2021-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210411_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, choices=[('269', 'Lào Cai'), ('268', 'Hưng Yên'), ('267', 'Hòa Bình'), ('266', 'Sơn La'), ('265', 'Điện Biên'), ('264', 'Lai Châu'), ('263', 'Yên Bái'), ('262', 'Bình Định'), ('261', 'Ninh Thuận'), ('260', 'Phú Yên'), ('259', 'Kon Tum'), ('258', 'Bình Thuận'), ('253', 'Bạc Liêu'), ('252', 'Cà Mau'), ('250', 'Hậu Giang'), ('249', 'Bắc Ninh'), ('248', 'Bắc Giang'), ('247', 'Lạng Sơn'), ('246', 'Cao Bằng'), ('245', 'Bắc Kạn'), ('244', 'Thái Nguyên'), ('243', 'Quảng Nam'), ('242', 'Quảng Ngãi'), ('241', 'Đắk Nông'), ('240', 'Tây Ninh'), ('239', 'Bình Phước'), ('238', 'Quảng Trị'), ('237', 'Quảng Bình'), ('236', 'Hà Tĩnh'), ('235', 'Nghệ An'), ('234', 'Thanh Hóa'), ('233', 'Ninh Bình'), ('232', 'Hà Nam'), ('231', 'Nam Định'), ('230', 'Quảng Ninh'), ('229', 'Phú Thọ'), ('228', 'Tuyên Quang'), ('227', 'Hà Giang'), ('226', 'Thái Bình'), ('225', 'Hải Dương'), ('224', 'Hải Phòng'), ('223', 'Thừa Thiên - Huế'), ('221', 'Vĩnh Phúc'), ('220', 'Cần Thơ'), ('219', 'Kiên Giang'), ('218', 'Sóc Trăng'), ('217', 'An Giang'), ('216', 'Đồng Tháp'), ('215', 'Vĩnh Long'), ('214', 'Trà Vinh'), ('213', 'Bến Tre'), ('212', 'Tiền Giang'), ('211', 'Long An'), ('210', 'Đắk Lắk'), ('209', 'Lâm Đồng'), ('208', 'Khánh Hòa'), ('207', 'Gia Lai'), ('206', 'Bà Rịa - Vũng Tàu'), ('205', 'Bình Dương'), ('204', 'Đồng Nai'), ('203', 'Đà Nẵng'), ('202', 'Hồ Chí Minh'), ('201', 'Hà Nội')], max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
