# Generated by Django 3.1.7 on 2021-07-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210705_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaddress',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='insurance_value',
            field=models.IntegerField(default=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='length',
            field=models.IntegerField(default=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='weight',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='width',
            field=models.IntegerField(default=65),
            preserve_default=False,
        ),
    ]
