# Generated by Django 3.1.8 on 2021-07-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210705_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaddress',
            name='ShopID_GHN',
            field=models.IntegerField(default=1732646),
            preserve_default=False,
        ),
    ]
